# Generated by Django 3.1.13 on 2022-01-05 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidence',
            name='date_reported',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='incidence',
            name='place',
            field=models.CharField(choices=[('Aguthi', 'Aguthi'), ('Chinga', 'Chinga'), ('Dedan Kimathi', 'Dedan Kimathi'), ('Endarasha/Mwiyogo', 'Endarasha/Mwiyogo'), ('Gakawa', 'Gakawa'), ('Gatarakwa', 'Gatarakwa'), ('Gatitu/Muruguru', 'Gatitu/Muruguru'), ('Gikondi', 'Gikondi'), ('Iriani (Mathira)', 'Iriani (Mathira)'), ('Iriaini (Othaya)', 'Iriaini (Othaya)'), ('Kabaru', 'Kabaru'), ('Kamakwa/Mukaro', 'Kamakwa/Mukaro'), ('Karatina', 'Karatina'), ('Karima', 'Karima'), ('Kiganjo/Mathari', 'Kiganjo/Mathari'), ('Kirimukuyu', 'Kirimukuyu'), ('Konyu', 'Konyu'), ('Magutu', 'Magutu'), ('Mahiga', 'Mahiga'), ('Mugunda', 'Mugunda'), ('Mukurweini-Central', 'Mukurweini-Central'), ('Mukurweini-West', 'Mukurweini-West'), ('Mweiga', 'Mweiga'), ('Narumoru/Kiamathaga', 'Narumoru/Kiamathaga'), ('Rugi', 'Rugi'), ('Ruguru', 'Ruguru'), ('Ruringu', 'Ruringu'), ('Rware', 'Rware'), ('Thegu', 'Thegu'), ('Wamagana', 'Wamagana')], max_length=200),
        ),
    ]
