# Generated by Django 3.1.13 on 2022-01-06 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0003_county'),
    ]

    operations = [
        migrations.DeleteModel(
            name='County',
        ),
    ]
